# Makefile to build the docker images.  Will leave some files to indicate what has been built.  Does 

DOCKER_REPO=hypersys


.built_librisp-build-1.0: librisp-build/1.0/Dockerfile
	docker build -t $(DOCKER_REPO)/librisp-build:1.0 librisp-build/1.0


