# hypersys/librisp-build:1.0
FROM hypersys/build:1.2
MAINTAINER Clint Webb <webb.clint@gmail.com>

# Based on the hypersys build image, and possibly modified to cater for the specific requirements of this project.






